apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cgraph-ingress
  namespace: cgraph
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.cgraph.org
      secretName: cgraph-tls
  rules:
    - host: api.cgraph.org
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: cgraph-backend
                port:
                  number: 8001
