apiVersion: v1
kind: Secret
metadata:
  name: cgraph-secrets
  namespace: cgraph
type: Opaque
stringData:
  DATABASE_URL: postgresql://cgraph:"1994Lks!Oliver2017."@postgres:5432/cgraph
  REDIS_URL: redis://redis:6379/0
  JWT_SECRET: your-super-secret-key-min-32-chars-long
  STRIPE_SECRET_KEY: sk_live_your_key
  SENDGRID_API_KEY: SG.your_key
  MATRIX_ACCESS_TOKEN: syt_cgraph_access_token